'''
A = float (input())
B = float (input())
MEDIA = ((A*3.5) + (B*7.5)) / 11
print ('MEDIA = %0.5f'%MEDIA)'''
'''
MEDIA = 0
A = float (input())
B = float (input())
C = float (input())

MEDIA = ((A*3) + (B*3) + (C*5)) / 3

print ('MEDIA {%0.5f}',MEDIA)'''

# estudando recursao
''' 
for c in range (6):
    print ('recursão')'''

def recursao():
    print('recursão')
    i += 1
    if i == 5:
        return
    else:
        recursao(i)

 

